version: '3'

services:
  jenkins:
    container_name: jenkins
    build: .
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8000:8080"
    restart: always 
    links:
      - sonarqube
  sonarqube:
    container_name: sonarqube
    image: sonarqube:alpine
    ports:
      - "9000:9000"
    links:
      - db
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
  db:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar