version: '3'

services:
  jenkins:
    build: .
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/jenkins/workspace:/var/jenkins_home/workspace
      - /tmp/jenkins/builds:/var/jenkins_home/builds
    ports:
        - "8080:8080"
    restart: always
    